// <auto-generated />
using AhorcadoPro.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AhorcadoPro.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207132347_InitialCreate")]
    partial class InitialCreate : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
